sudo: required
services:
  - docker

env:
  - DOCKER_IMAGE=iampeternguyen/docker-react

before_install:
  - docker build -t $DOCKER_IMAGE -f Dockerfile.dev .

script:
  - docker run $DOCKER_IMAGE npm run test -- --watchAll=false